// This file is @generated by prost-build.
/// LogTarget defines matching and actions for logs.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogTarget {
    /// Matchers to identify which logs this policy applies to (AND logic)
    #[prost(message, repeated, tag = "1")]
    pub r#match: ::prost::alloc::vec::Vec<LogMatcher>,
    /// The keep field controls whether matching telemetry survives. It unifies
    /// dropping, sampling, and rate limiting into a single concept: what percentage
    /// or amount of matching telemetry continues to the next stage?
    ///
    /// Valid values:
    ///    "all"  - Keep everything (default, can be omitted)
    ///    "none" - Drop everything
    ///    "N%"   - Keep N percent (0-100), e.g. "50%"
    ///    "N/s"  - Keep at most N per second, e.g. "100/s"
    ///    "N/m"  - Keep at most N per minute, e.g. "1000/m"
    #[prost(string, tag = "2")]
    pub keep: ::prost::alloc::string::String,
    /// Transform operations to apply
    #[prost(message, optional, tag = "3")]
    pub transform: ::core::option::Option<LogTransform>,
}
/// LogMatcher provides a way to match against log telemetry data using known fields.
///
/// IMPORTANT CONSTRAINTS:
/// - Multiple matchers are ANDed together: all matchers must match for the
///    overall match to succeed.
/// - The list of matchers should uniquely identify a specific pattern of telemetry
///    for that policy. Matchers should NOT be used as a catch-all; they should be
///    specific enough to target the intended telemetry precisely.
///
/// All regex fields use RE2 syntax for consistency across implementations.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogMatcher {
    /// If true, inverts the match result
    #[prost(bool, tag = "20")]
    pub negate: bool,
    /// FIELD SELECTION (keep in sync with LogRedact, LogRename, LogAdd, LogRemove)
    /// The field to match against. Exactly one must be set.
    #[prost(oneof = "log_matcher::Field", tags = "1, 2, 3, 4")]
    pub field: ::core::option::Option<log_matcher::Field>,
    /// Match type. Exactly one must be set.
    #[prost(oneof = "log_matcher::Match", tags = "10, 11, 12")]
    pub r#match: ::core::option::Option<log_matcher::Match>,
}
/// Nested message and enum types in `LogMatcher`.
pub mod log_matcher {
    /// FIELD SELECTION (keep in sync with LogRedact, LogRename, LogAdd, LogRemove)
    /// The field to match against. Exactly one must be set.
    #[derive(serde::Serialize, serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Field {
        /// Simple fields (body, severity_text, trace_id, span_id, etc.)
        #[prost(enumeration = "super::LogField", tag = "1")]
        LogField(i32),
        /// Log record attribute by key
        #[prost(string, tag = "2")]
        LogAttribute(::prost::alloc::string::String),
        /// Resource attribute by key
        #[prost(string, tag = "3")]
        ResourceAttribute(::prost::alloc::string::String),
        /// Scope attribute by key
        #[prost(string, tag = "4")]
        ScopeAttribute(::prost::alloc::string::String),
    }
    /// Match type. Exactly one must be set.
    #[derive(serde::Serialize, serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Match {
        /// Exact string match
        #[prost(string, tag = "10")]
        Exact(::prost::alloc::string::String),
        /// Regular expression match
        #[prost(string, tag = "11")]
        Regex(::prost::alloc::string::String),
        /// Field existence check
        #[prost(bool, tag = "12")]
        Exists(bool),
    }
}
/// LogTransform defines modifications to logs.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogTransform {
    /// Fields to remove
    #[prost(message, repeated, tag = "1")]
    pub remove: ::prost::alloc::vec::Vec<LogRemove>,
    /// Fields to redact
    #[prost(message, repeated, tag = "2")]
    pub redact: ::prost::alloc::vec::Vec<LogRedact>,
    /// Fields to rename
    #[prost(message, repeated, tag = "3")]
    pub rename: ::prost::alloc::vec::Vec<LogRename>,
    /// Fields to add
    #[prost(message, repeated, tag = "4")]
    pub add: ::prost::alloc::vec::Vec<LogAdd>,
}
/// LogRemove removes a field.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogRemove {
    /// FIELD SELECTION (keep in sync with LogMatcher, LogRedact, LogRename, LogAdd)
    /// The field to remove. Exactly one must be set.
    #[prost(oneof = "log_remove::Field", tags = "1, 2, 3, 4")]
    pub field: ::core::option::Option<log_remove::Field>,
}
/// Nested message and enum types in `LogRemove`.
pub mod log_remove {
    /// FIELD SELECTION (keep in sync with LogMatcher, LogRedact, LogRename, LogAdd)
    /// The field to remove. Exactly one must be set.
    #[derive(serde::Serialize, serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Field {
        /// Simple fields (body, severity_text, trace_id, span_id, etc.)
        #[prost(enumeration = "super::LogField", tag = "1")]
        LogField(i32),
        /// Log record attribute by key
        #[prost(string, tag = "2")]
        LogAttribute(::prost::alloc::string::String),
        /// Resource attribute by key
        #[prost(string, tag = "3")]
        ResourceAttribute(::prost::alloc::string::String),
        /// Scope attribute by key
        #[prost(string, tag = "4")]
        ScopeAttribute(::prost::alloc::string::String),
    }
}
/// LogRedact masks a field value.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogRedact {
    /// Replacement value (e.g., "\[REDACTED\]")
    #[prost(string, tag = "10")]
    pub replacement: ::prost::alloc::string::String,
    /// FIELD SELECTION (keep in sync with LogMatcher, LogRemove, LogRename, LogAdd)
    /// The field to redact. Exactly one must be set.
    #[prost(oneof = "log_redact::Field", tags = "1, 2, 3, 4")]
    pub field: ::core::option::Option<log_redact::Field>,
}
/// Nested message and enum types in `LogRedact`.
pub mod log_redact {
    /// FIELD SELECTION (keep in sync with LogMatcher, LogRemove, LogRename, LogAdd)
    /// The field to redact. Exactly one must be set.
    #[derive(serde::Serialize, serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Field {
        /// Simple fields (body, severity_text, trace_id, span_id, etc.)
        #[prost(enumeration = "super::LogField", tag = "1")]
        LogField(i32),
        /// Log record attribute by key
        #[prost(string, tag = "2")]
        LogAttribute(::prost::alloc::string::String),
        /// Resource attribute by key
        #[prost(string, tag = "3")]
        ResourceAttribute(::prost::alloc::string::String),
        /// Scope attribute by key
        #[prost(string, tag = "4")]
        ScopeAttribute(::prost::alloc::string::String),
    }
}
/// LogRename changes a field name.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogRename {
    /// The new field name
    #[prost(string, tag = "10")]
    pub to: ::prost::alloc::string::String,
    /// If true, overwrites the target field if it already exists
    #[prost(bool, tag = "11")]
    pub upsert: bool,
    /// FIELD SELECTION (keep in sync with LogMatcher, LogRemove, LogRedact, LogAdd)
    /// The field to rename. Exactly one must be set.
    #[prost(oneof = "log_rename::From", tags = "1, 2, 3, 4")]
    pub from: ::core::option::Option<log_rename::From>,
}
/// Nested message and enum types in `LogRename`.
pub mod log_rename {
    /// FIELD SELECTION (keep in sync with LogMatcher, LogRemove, LogRedact, LogAdd)
    /// The field to rename. Exactly one must be set.
    #[derive(serde::Serialize, serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum From {
        /// Simple fields (body, severity_text, trace_id, span_id, etc.)
        #[prost(enumeration = "super::LogField", tag = "1")]
        FromLogField(i32),
        /// Log record attribute by key
        #[prost(string, tag = "2")]
        FromLogAttribute(::prost::alloc::string::String),
        /// Resource attribute by key
        #[prost(string, tag = "3")]
        FromResourceAttribute(::prost::alloc::string::String),
        /// Scope attribute by key
        #[prost(string, tag = "4")]
        FromScopeAttribute(::prost::alloc::string::String),
    }
}
/// LogAdd inserts a field.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogAdd {
    /// The value to set
    #[prost(string, tag = "10")]
    pub value: ::prost::alloc::string::String,
    /// If true, overwrites the field if it already exists
    #[prost(bool, tag = "11")]
    pub upsert: bool,
    /// FIELD SELECTION (keep in sync with LogMatcher, LogRemove, LogRedact, LogRename)
    /// The field to add. Exactly one must be set.
    #[prost(oneof = "log_add::Field", tags = "1, 2, 3, 4")]
    pub field: ::core::option::Option<log_add::Field>,
}
/// Nested message and enum types in `LogAdd`.
pub mod log_add {
    /// FIELD SELECTION (keep in sync with LogMatcher, LogRemove, LogRedact, LogRename)
    /// The field to add. Exactly one must be set.
    #[derive(serde::Serialize, serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Field {
        /// Simple fields (body, severity_text, trace_id, span_id, etc.)
        #[prost(enumeration = "super::LogField", tag = "1")]
        LogField(i32),
        /// Log record attribute by key
        #[prost(string, tag = "2")]
        LogAttribute(::prost::alloc::string::String),
        /// Resource attribute by key
        #[prost(string, tag = "3")]
        ResourceAttribute(::prost::alloc::string::String),
        /// Scope attribute by key
        #[prost(string, tag = "4")]
        ScopeAttribute(::prost::alloc::string::String),
    }
}
/// LogField identifies simple log fields (non-keyed).
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LogField {
    Unspecified = 0,
    /// Log record fields
    Body = 1,
    SeverityText = 2,
    TraceId = 3,
    SpanId = 4,
    EventName = 5,
    /// Schema URLs
    ResourceSchemaUrl = 10,
    ScopeSchemaUrl = 11,
}
impl LogField {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "LOG_FIELD_UNSPECIFIED",
            Self::Body => "LOG_FIELD_BODY",
            Self::SeverityText => "LOG_FIELD_SEVERITY_TEXT",
            Self::TraceId => "LOG_FIELD_TRACE_ID",
            Self::SpanId => "LOG_FIELD_SPAN_ID",
            Self::EventName => "LOG_FIELD_EVENT_NAME",
            Self::ResourceSchemaUrl => "LOG_FIELD_RESOURCE_SCHEMA_URL",
            Self::ScopeSchemaUrl => "LOG_FIELD_SCOPE_SCHEMA_URL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LOG_FIELD_UNSPECIFIED" => Some(Self::Unspecified),
            "LOG_FIELD_BODY" => Some(Self::Body),
            "LOG_FIELD_SEVERITY_TEXT" => Some(Self::SeverityText),
            "LOG_FIELD_TRACE_ID" => Some(Self::TraceId),
            "LOG_FIELD_SPAN_ID" => Some(Self::SpanId),
            "LOG_FIELD_EVENT_NAME" => Some(Self::EventName),
            "LOG_FIELD_RESOURCE_SCHEMA_URL" => Some(Self::ResourceSchemaUrl),
            "LOG_FIELD_SCOPE_SCHEMA_URL" => Some(Self::ScopeSchemaUrl),
            _ => None,
        }
    }
}
/// Policy represents a complete telemetry policy definition.
/// Policies are designed to be:
/// - Implementation Agnostic: Works in SDK, Collector, or any component
/// - Standalone: No need to understand pipeline configuration
/// - Dynamic: Can be updated post-instantiation
/// - Idempotent: Safe to apply to multiple components
/// - Fail-Open: Does not interfere with telemetry on failure
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Policy {
    /// Unique identifier for this policy
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Human-readable name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Optional description
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    /// Whether this policy is enabled
    #[prost(bool, tag = "4")]
    pub enabled: bool,
    /// Timestamp when this policy was created (Unix epoch nanoseconds)
    #[prost(fixed64, tag = "5")]
    #[serde(
        serialize_with = "crate::proto::serde_helpers::serialize_u64_as_string",
        deserialize_with = "crate::proto::serde_helpers::deserialize_u64_from_string"
    )]
    pub created_at_unix_nano: u64,
    /// Timestamp when this policy was last modified (Unix epoch nanoseconds)
    #[prost(fixed64, tag = "6")]
    #[serde(
        serialize_with = "crate::proto::serde_helpers::serialize_u64_as_string",
        deserialize_with = "crate::proto::serde_helpers::deserialize_u64_from_string"
    )]
    pub modified_at_unix_nano: u64,
    /// Labels for metadata and routing
    #[prost(message, repeated, tag = "7")]
    pub labels: ::prost::alloc::vec::Vec<
        super::super::super::opentelemetry::proto::common::v1::KeyValue,
    >,
    /// Target configuration. Exactly one must be set.
    #[prost(oneof = "policy::Target", tags = "10")]
    #[serde(flatten)]
    pub target: ::core::option::Option<policy::Target>,
}
/// Nested message and enum types in `Policy`.
pub mod policy {
    /// Target configuration. Exactly one must be set.
    #[derive(serde::Serialize, serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Target {
        /// MetricTarget metric = 11; // Reserved for future use
        #[prost(message, tag = "10")]
        Log(super::LogTarget),
    }
}
/// ClientMetadata contains information about the client requesting policies.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientMetadata {
    /// Policy stages this client supports
    #[prost(enumeration = "PolicyStage", repeated, tag = "1")]
    pub supported_policy_stages: ::prost::alloc::vec::Vec<i32>,
    /// Additional metadata labels
    /// NOTE FOR TERO:
    /// * workspace.id is required for usage.
    #[prost(message, repeated, tag = "2")]
    pub labels: ::prost::alloc::vec::Vec<
        super::super::super::opentelemetry::proto::common::v1::KeyValue,
    >,
    /// Resource attributes describing this client's identity
    /// REQUIRED:
    /// * service.instance.id
    /// * service.name
    /// * service.namespace
    /// * service.version
    #[prost(message, repeated, tag = "3")]
    pub resource_attributes: ::prost::alloc::vec::Vec<
        super::super::super::opentelemetry::proto::common::v1::KeyValue,
    >,
}
/// TransformStageStatus reports hits and misses for a single transform stage.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TransformStageStatus {
    /// Number of times this stage was applied.
    #[prost(int64, tag = "1")]
    #[serde(
        serialize_with = "crate::proto::serde_helpers::serialize_i64_as_string",
        deserialize_with = "crate::proto::serde_helpers::deserialize_i64_from_string"
    )]
    pub hits: i64,
    /// Number of times this stage was evaluated but the field selected nothing.
    #[prost(int64, tag = "2")]
    #[serde(
        serialize_with = "crate::proto::serde_helpers::serialize_i64_as_string",
        deserialize_with = "crate::proto::serde_helpers::deserialize_i64_from_string"
    )]
    pub misses: i64,
}
/// PolicySyncStatus reports the status of an individual policy during sync.
/// Used to communicate policy execution metrics and errors back to the provider.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PolicySyncStatus {
    /// The policy ID this status refers to.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Number of times this policy matched telemetry since the last sync.
    #[prost(int64, tag = "2")]
    #[serde(
        serialize_with = "crate::proto::serde_helpers::serialize_i64_as_string",
        deserialize_with = "crate::proto::serde_helpers::deserialize_i64_from_string"
    )]
    pub match_hits: i64,
    /// Number of times this policy was evaluated but did not match.
    #[prost(int64, tag = "3")]
    #[serde(
        serialize_with = "crate::proto::serde_helpers::serialize_i64_as_string",
        deserialize_with = "crate::proto::serde_helpers::deserialize_i64_from_string"
    )]
    pub match_misses: i64,
    /// Error messages encountered while applying this policy.
    #[prost(string, repeated, tag = "4")]
    pub errors: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Transform stage statistics
    #[prost(message, optional, tag = "10")]
    pub remove: ::core::option::Option<TransformStageStatus>,
    #[prost(message, optional, tag = "11")]
    pub redact: ::core::option::Option<TransformStageStatus>,
    #[prost(message, optional, tag = "12")]
    pub rename: ::core::option::Option<TransformStageStatus>,
    #[prost(message, optional, tag = "13")]
    pub add: ::core::option::Option<TransformStageStatus>,
}
/// SyncRequest is sent by clients to request policy updates.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncRequest {
    /// Client identification and capabilities
    #[prost(message, optional, tag = "1")]
    pub client_metadata: ::core::option::Option<ClientMetadata>,
    /// Request full sync (ignore policy_statuses)
    #[prost(bool, tag = "2")]
    pub full_sync: bool,
    /// Last sync timestamp (Unix epoch nanoseconds)
    #[prost(fixed64, tag = "3")]
    #[serde(
        serialize_with = "crate::proto::serde_helpers::serialize_u64_as_string",
        deserialize_with = "crate::proto::serde_helpers::deserialize_u64_from_string"
    )]
    pub last_sync_timestamp_unix_nano: u64,
    /// The hash of the policy list as last received by the client.
    #[prost(string, tag = "4")]
    pub last_successful_hash: ::prost::alloc::string::String,
    /// Status of individual policies within this set.
    #[prost(message, repeated, tag = "5")]
    pub policy_statuses: ::prost::alloc::vec::Vec<PolicySyncStatus>,
}
/// SyncResponse contains policy updates for the client.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncResponse {
    /// The policies to sync
    #[prost(message, repeated, tag = "1")]
    pub policies: ::prost::alloc::vec::Vec<Policy>,
    /// Hash of the entire list of policies (for change detection)
    #[prost(string, tag = "2")]
    pub hash: ::prost::alloc::string::String,
    /// Timestamp of this sync (Unix epoch nanoseconds)
    #[prost(fixed64, tag = "3")]
    #[serde(
        serialize_with = "crate::proto::serde_helpers::serialize_u64_as_string",
        deserialize_with = "crate::proto::serde_helpers::deserialize_u64_from_string"
    )]
    pub sync_timestamp_unix_nano: u64,
    /// Suggested interval before next sync (in seconds)
    #[prost(uint32, tag = "4")]
    pub recommended_sync_interval_seconds: u32,
    /// Whether this is a full replacement or incremental update
    #[prost(enumeration = "SyncType", tag = "5")]
    #[serde(with = "crate::proto::serde_helpers::sync_type")]
    pub sync_type: i32,
    /// Error message if sync failed
    #[prost(string, tag = "6")]
    pub error_message: ::prost::alloc::string::String,
}
/// PolicyStage identifies the execution stage for a policy.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PolicyStage {
    Unspecified = 0,
    /// Log filtering stage (keep/drop decisions)
    LogFilter = 1,
    /// Log transformation stage (field modifications)
    LogTransform = 2,
}
impl PolicyStage {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "POLICY_STAGE_UNSPECIFIED",
            Self::LogFilter => "POLICY_STAGE_LOG_FILTER",
            Self::LogTransform => "POLICY_STAGE_LOG_TRANSFORM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "POLICY_STAGE_UNSPECIFIED" => Some(Self::Unspecified),
            "POLICY_STAGE_LOG_FILTER" => Some(Self::LogFilter),
            "POLICY_STAGE_LOG_TRANSFORM" => Some(Self::LogTransform),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SyncType {
    Unspecified = 0,
    Full = 1,
}
impl SyncType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SYNC_TYPE_UNSPECIFIED",
            Self::Full => "SYNC_TYPE_FULL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SYNC_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "SYNC_TYPE_FULL" => Some(Self::Full),
            _ => None,
        }
    }
}
/// Generated client implementations.
#[cfg(feature = "grpc")]
pub mod policy_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// PolicyService defines the gRPC service for policy providers.
    #[derive(Debug, Clone)]
    pub struct PolicyServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl PolicyServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> PolicyServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> PolicyServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            PolicyServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Sync policies with the provider
        pub async fn sync(
            &mut self,
            request: impl tonic::IntoRequest<super::SyncRequest>,
        ) -> std::result::Result<tonic::Response<super::SyncResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tero.policy.v1.PolicyService/Sync",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("tero.policy.v1.PolicyService", "Sync"));
            self.inner.unary(req, path, codec).await
        }
    }
}
